spring:
  profiles:
    active: local

  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wtapps
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_seq: true
        format_sql: true


  sql:
    init:
      mode: always  # 애플리케이션이 시작될 때 쿼리 실행을 허용

logging:
  level:
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework: INFO
    com.example.demo: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG



#logging:
#  level:
#    root:

